### PR TITLE
remove mentions of ProximableFunction

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
The failures are due to the dreaded Arpack.jl. They've nothing to do with the changes in this PR.

**Comment by dpo** [comment]
@rjbaraldi Does this look ok to you?

**Comment by rjbaraldi** [comment]
I'm a little confused, what does this do exactly?

**Comment by dpo** [comment]
The type ProximableFunction no longer exists in ProximalOperators, c.f., https://github.com/JuliaSmoothOptimizers/ShiftedProximalOperators.jl/pull/64.

**Comment by rjbaraldi** [comment]
So do we have to change shiftedproximaloperators as well?

**Comment by dpo** [comment]
Makes sense or not?

**Comment by dpo** [comment]
What abstract type? It's already changed in ShiftedProxOps. See the link above.

**Review by rjbaraldi — APPROVED** [review]
Seems like it remains compatible with SPO, so go ahead.

**Pull request merged**
